# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128)),
                ('logout_time', models.CharField(max_length=128)),
                ('is_active', models.CharField(max_length=128)),
                ('deviec_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='login_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.User_table'),
        ),
    ]
